"""test3

Revision ID: 8a280e3e47e7
Revises: cf81f68d765a
Create Date: 2021-06-28 12:04:23.568359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a280e3e47e7'
down_revision = 'cf81f68d765a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('uq_message_content', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_message_content', ['content'])

    # ### end Alembic commands ###
