"""Users DB

Revision ID: d57a1802f6b8
Revises: 
Create Date: 2021-06-11 11:41:37.344114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57a1802f6b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'user')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('send_user', sa.Integer(), nullable=True),
    sa.Column('rec_user', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('user',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=21), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('user_picture',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pictures', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_picture')
    op.drop_table('user')
    op.drop_table('message')
    op.drop_table('chat')
    # ### end Alembic commands ###
